name: Build and Push Docker Image

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build-and-push:
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Bun dependencies
        uses: actions/cache@v3
        with:
          path: |
            .bun
            node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Set Docker tag
        id: docker_tag
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            echo "TAG=latest-dev" >> $GITHUB_ENV
          else
            echo "TAG=latest" >> $GITHUB_ENV
          fi

      - name: Build Docker image
        run: |
          docker build . -t bunnybunbun37204/cusw-frontend:${{ env.TAG }} \
            --build-arg GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} \
            --build-arg GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} \
            --build-arg NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}

      - name: Push Docker image to Docker Hub
        run: docker push bunnybunbun37204/cusw-frontend:${{ env.TAG }}

  code-check:
    if: github.event_name == 'pull_request' && github.ref != 'refs/heads/dev' && github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'

      - name: Verify Bun installation
        run: |
          bun --version

      - name: Lint code
        run: |
          echo "Running lint checks..."
          bun run lint
